config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: :callbacks }
  resources :tweets do
    resources :likes
  end
  resources :tweets do
    resources :tweets
  end
  resources :users

  root to: "tweets#index"

  # <api>
  # GWT |POST /api/article GET | PUT | DELETE
  namespace :api do
    resources :users do
      resources :tweets do
        resources :tweets
      end
    end
    resources :tweets do
      resources :tweets
    end
    resources :tweets, except: %i[new edit] do
      resources :likes, only: :create
    end
    resources :likes, only: :destroy

    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
  end

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  # Associations
  belongs_to :user
  has_many :retweets, class_name: "Tweet",
           foreign_key: "replied_to_id",
           dependent: :destroy,
           inverse_of: "replied_to"

  belongs_to :replied_to, class_name: "Tweet", counter_cache: :replies_count, optional: true

  has_many :likes,  dependent: :destroy

  # Validations
  validates :body, presence: true
  validates :body, length: { maximum: 140 }

end

# class Task < ActiveRecord::Base
#   belongs_to :sub_task, class_name: Task.name, touch: true, counter_cache: :sub_tasks_count
#   has_many :sub_tasks, class_name: Task.name, foreign_key: :sub_task_id, dependent: :destroy
# end

app/controllers/api/tweets_controller.rb
module Api
  class TweetsController < ApiController
    before_action :set_tweet, only: %i[show update destroy ]

    # GET /tweets
    def index
      render json: Tweet.all, status: :ok
    end

    # GET /tweets/1
    def show
      render json: @tweet, status: :ok
    end

    # POST /tweets
    # POST /users/:user_id/tweets
    def create
      @tweet = Tweet.create(body: tweet_params[:body], user_id: params[:user_id])
      @tweet.replied_to_id = params[:tweet_id] unless params[:tweet_id].nil?

      if @tweet.save
        render json: @tweet, status: :created
      else
        render json: {errors: @tweet.errors}, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /tweets/1
    def update
      if @tweet.update(tweet_params)
        render json: @tweet, status: :ok
      else
        render json: {errors: @tweet.errors}, status: :unprocessable_entity
      end
    end

    # DELETE /tweets/1
    def destroy
      @tweet.destroy
      head :no_content
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:body, :user_id)
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[show edit update destroy ]

  # GET /tweets
  def index
    @tweets = Tweet.all.select { |tweet| tweet.replied_to_id.nil? }.sort_by(&:created_at).reverse!
    @tweet_new = Tweet.new
    @tweets_of_current_user = Like.where(user_id: current_user.id).map(&:tweet) if current_user
  end

  # GET /tweets/1
  def show
    @tweet_new = Tweet.new
    @retweets = @tweet.retweets.sort_by(&:created_at).reverse!
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit; end

  # POST /tweets
  # POST /users/:user_id/tweets
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    @tweet.replied_to_id = params[:tweet_id] unless params[:tweet_id].nil?

    if @tweet.save
      redirect_back_or_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tweets/1
  def update
    if @tweet.update(tweet_params)
      redirect_to root_path, notice: "Tweet was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet.destroy
    redirect_back_or_to root_path, notice: "Tweet was successfully destroyed.", status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tweet_params
    params.require(:tweet).permit(:body)
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
  TIME_PATTERN = {
    " hours" => "h",
    " minutes" => "m",
    " days" => "d",
    " hour" => "h",
    " minute" => "m",
    " day" => "d",
    "about" => ""
  }.freeze

  def time_ago_converter(words)
    TIME_PATTERN.each_pair do |k, v|
      words.gsub!(k, v)
    end
    words
  end
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, class: "mb-4") do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text-center pd-2 bg-white mb-4">
    <%= form_with model: @tweet, method: :patch, data: { turbo: "false" } do |f| %>
      <div class="flex flex-column">
        <%= f.text_area :body, placeholder: "Remember to thing before write...", id: "text_area"%>
        <%= f.submit "Update", class: "button button--tweet align-end"%>
      </div>
    <%end%>
  </div>

<% end %>

app/views/tweets/_tweet.html.erb
  <div class="card__tweet">
    <div class="card__avatar">
      <% if tweet.user.avatar.attached? %>
        <%= link_to (image_tag tweet.user.avatar, class: "avatar"), user_path(tweet.user) %>
      <% else %>
        <%= link_to (image_tag "icon/avatar.svg", class: "avatar"), user_path(tweet.user) %>
      <% end %>
    </div>

    <div id="<%= dom_id tweet %>" class="card__tweet--body">
      <div class="tweet__header">
        <div>
          <span class="username"><%= link_to (tweet.user.name), user_path(tweet.user) %></span>
          <span class="name">@<%= link_to (tweet.user.username), user_path(tweet.user)  %></span>
        </div>
        <span class="time"><%= time_ago_in_words(tweet.created_at) %></span>
      </div>

      <p class="tweet_main"><%= link_to (tweet.body), tweet_path(tweet) %> </p>

      <div class="tweet__footer space-btw center-ver">
        <% if policy(tweet).edit? %>
          <div class="flex gap-2 center-ver">
            <%=link_to (image_tag "icon/trash.svg", class: "icon"), tweet_path(tweet), data: {turbo_method: :delete} %>
            <%=link_to (image_tag "icon/edit.svg", class: "icon"), edit_tweet_path(tweet) %>
          </div>
        <% end %>

        <div class="flex gap-2 center-ver">
          <%= image_tag "icon/cloud.svg" %>
          <span class="content-m color-secondary"><%= tweet.replies_count %></span>
          <% if current_user && (@tweets_of_current_user&.include? tweet) %>
            <%= button_to (image_tag "icon/loved_red.svg"), tweet_likes_path(tweet), class: "whithout_formate" %>
            <span class="content-m color-secondary"><%= tweet.likes_count %></span>
          <% else %>
            <%= button_to (image_tag "icon/loved.svg"), tweet_likes_path(tweet), class: "whithout_formate flex center" %>
            <span class="content-m color-secondary"><%= tweet.likes_count %></span>
          <% end%>
        </div>
      </div>
    </div>

  </div>

app/views/tweets/edit.html.erb
<h1 class="heading--sm mb-4 mt-4 flex center">Edit tweet</h1>

<%= render "form", tweet: @tweet %>

<div class="flex center">
  <%= button_to "Cancel" ,tweet_path(@tweet.id), method: :get, class: "whithout_formate mb-4 button button--primary"%>
</div>

app/views/tweets/index.html.erb
<section class="container__sm">
  <div class="text-center mb-4 mt-4">
    <h1><%= link_to "Home", root_path, class:"upcase" %></h1>
  </div>

  <% if user_signed_in? %>
    <div class="text-center pd-2 bg-white mb-4">
      <%= form_with model: @tweet_new, data: { turbo: "false" }, class: "flex flex-end gap-2 strech" do |f| %>
        <%= f.text_area :body, placeholder: "Remember to thing before write...", id: "text_area", class: "flex center-hor"%>
        <%= f.submit "Tweet", class: "button button--tweet"%>
      <%end%>
    </div>
  <% end%>

  <div id="tweets">
    <%= render @tweets %>
  </div>
</section>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<section class="container__sm">
  <p style: "color: green"><%= notice %></p>
  <h1 class="content-l bold flex center-hor mb-4 mt-4">Tweet Details</h1>
  <section class="mb-4 "><%= render @tweet %> </section>

  <hr>
  
  <% if user_signed_in? %>
    <div class="text-center pd-2 bg-white mb-4">
      <%= form_with model: [@tweet, @tweet_new], method: :post, data: { turbo: "false" } do |f| %>
        <div class="flex flex-column">
          <%= f.text_area :body, placeholder: "Remember to thing before write...", id: "text_area"%>
          <%= f.submit "Tweet", class: "button button--tweet align-end upcase"%>
        </div>
      <%end%>
    </div>
  <% end %>

  <section ><%= render @retweets %></section>

  <div class="flex center">
    <% link_to "Back to tweets", tweets_path %>
  </div>
</section> 